[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
